version: '3.9'  # Version recommandée (moderne et compatible)

services:
  backend:
    build: .              # Construit à partir du Dockerfile dans le répertoire courant
    ports:
      - "8008:8008"       # Redirige le port 8008 du conteneur vers le port 8008 de l'hôte
    networks:
      - backend-network   # Se connecte au réseau nommé
    restart: unless-stopped  # Redémarre automatiquement sauf si tu l’arrêtes manuellement
    environment:
      - NODE_ENV=production  # Définit l'environnement d'exécution

networks:
  backend-network:
    driver: bridge         # Utilise le driver bridge (par défaut mais bien de le préciser)
