on:
  push:
    branches:
      - main
jobs:
  Build-for-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: "17" # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64
      # - uses: expo/expo-github-action@v5
      #   with:
      #     expo-version: 3.x
      #     # expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
      #     # expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Install deps
        run: cd packages/frontend && npm i && npx expo prebuild
      - name: Build Android APK Bundle
        run: cd packages/frontend/android && ./gradlew app:assembleRelease
      - uses: actions/upload-artifact@v4
        with:
          name: bundle
          path: packages/frontend/android/app/build/outputs/apk/release/app-release.apk
